"""
Tests for topic modelling module.
"""
from os import mkdir
from os.path import join
import unittest

from shutil import rmtree
from pandas import DataFrame, read_csv

from corpus_distance.data_preprocessing import topic_modelling as tm

from tests.mocks.data_preprocessing import (
    TEXT_FOR_TOPIC_MODELLING_POLACK,
    TOPIC_MODELLED_TOKENS_POLACK,
    TEXT_FOR_TOPIC_MODELLING_NOVGOROD,
    TOPIC_MODELLED_TOKENS_NOVGOROD,
    INCORRECT_ARGS_BUILD_TOPIC_WORDS_FOR_LECT,
    INCORRECT_ARGS_SAVE_TOPIC_MODELLING_RESULTS,
    TOPIC_MODELLING_CORRECT_ARGS
)
class TestSetTopicRange(unittest.TestCase):
    """
    Tests function set_topic_range.
    """

    def test_set_topic_range_bad_cases(self):
        """
        Checks bad cases: negative numbers for topic range (both start and finish),
        as well as user-given range of topics to take getting out of bounds of
        the generated topics range.
        """
        wrong_params = tm.LDAParams()
        cases = [{"start": case[0], "num": case[1]} for case in [
            (None, 15),
            (None, -1),
            (7, 5),
            (-1, None)
        ]]

        for case in cases:
            with self.subTest(data=case):
                wrong_params.required_topics_start = case["start"]
                wrong_params.required_topics_num = case["num"]
                self.assertRaises(ValueError, tm.set_topic_range, wrong_params)


    def test_set_topic_range_good_cases_custom_number(self):
        """
        Covers case of restricted from the top topic range, in which the user
        wants to take the number of topics, which is less than the number of
        topics, generated by the model, starting from the first (index 0) topic.
        """
        params = tm.LDAParams(required_topics_num=5)

        first_topic, last_topic = tm.set_topic_range(params)

        self.assertEqual(first_topic, 0)
        self.assertEqual(last_topic, 5)

    def test_set_topic_range_good_cases_custom_start(self):
        """
        Covers case of restricted from the top topic range, in which the user
        wants to take all the topics, generated by the model,
        starting from the topic, index of which user provides.
        """
        params = tm.LDAParams(required_topics_start=2)

        first_topic, last_topic = tm.set_topic_range(params)

        self.assertEqual(first_topic, 2)
        self.assertEqual(last_topic, 10)

    def test_set_topic_range_good_cases_custom_number_and_start(self):
        """
        Covers case of restricted from the top topic range, in which the user
        wants to take the number of topics, which is less than the number of
        topics, generated by the model, starting from the topic, index of which user provides.
        """
        params = tm.LDAParams(required_topics_start=5, required_topics_num=5)

        first_topic, last_topic = tm.set_topic_range(params)

        self.assertEqual(first_topic, 5)
        self.assertEqual(last_topic, 10)



    def test_set_topic_range_default_case(self):
        """
        Covers the default case, without any user modifications of the first topic to
        take and the range of topics to take.
        """
        first_topic, last_topic = tm.set_topic_range()

        self.assertEqual(first_topic, 0)
        self.assertEqual(last_topic, 10)


class TestBuildTopicWordsForLect(unittest.TestCase):
    """
    Assures the correct functioning of the build_topic_words_for_lects function.
    """

    def test_build_topic_words_for_lect_negative_cases_data_frame(self):
        """
        Checks, whether the function correctly processes the incorrect data_frame argument.
        """
        cases = [{"frame": case} for case in INCORRECT_ARGS_BUILD_TOPIC_WORDS_FOR_LECT]
        for case in cases:
            with self.subTest(data=case):
                self.assertRaises(
                    ValueError,
                    tm.build_topic_words_for_lect,
                    case["frame"],
                    "Croatian", 1, 5, tm.LDAParams()
                )

    def test_build_topic_words_for_lect_negative_cases_lect(self):
        """
        Checks, whether the function correctly processes the incorrect lect argument.
        """
        cases = [{"lect": case} for case in INCORRECT_ARGS_BUILD_TOPIC_WORDS_FOR_LECT]
        for case in cases:
            with self.subTest(data=case):
                self.assertRaises(
                    ValueError,
                    tm.build_topic_words_for_lect,
                    TOPIC_MODELLING_CORRECT_ARGS["initial"],
                    case["lect"], 1, 5, tm.LDAParams()
                )


    def test_build_topic_words_for_lect_negative_cases_start_topic(self):
        """
        Checks, whether the function correctly processes the incorrect first_topic argument.
        """
        cases = [{"start_topic": case} for case in INCORRECT_ARGS_BUILD_TOPIC_WORDS_FOR_LECT]
        for case in cases:
            with self.subTest(data=case):
                self.assertRaises(
                    ValueError,
                    tm.build_topic_words_for_lect,
                    TOPIC_MODELLING_CORRECT_ARGS["initial"],
                    "Croatian", case["start_topic"], 5, tm.LDAParams()
                )


    def test_build_topic_words_for_lect_negative_cases_end_topic(self):
        """
        Checks, whether the function correctly processes the incorrect 
        topic_range_limit argument.
        """
        cases = [{"end_topic": case} for case in INCORRECT_ARGS_BUILD_TOPIC_WORDS_FOR_LECT]
        for case in cases:
            with self.subTest(data=case):
                self.assertRaises(
                    ValueError,
                    tm.build_topic_words_for_lect,
                    TOPIC_MODELLING_CORRECT_ARGS["initial"],
                    "Croatian", 1, case["end_topic"], tm.LDAParams()
                )


    def test_build_topic_words_for_lect_negative_cases_lda_params(self):
        """
        Checks, whether the function correctly processes the incorrect lda_params argument.
        """
        cases = [{"bad_params": case} for case in INCORRECT_ARGS_BUILD_TOPIC_WORDS_FOR_LECT]
        for case in cases:
            with self.subTest(data=case):
                self.assertRaises(
                    ValueError,
                    tm.build_topic_words_for_lect,
                    TOPIC_MODELLING_CORRECT_ARGS["initial"],
                    "Croatian", 1, 3, case["bad_params"]
                )


    def test_build_topic_words_for_lect_positive_case(self):
        """
        Checks, whether the function steadily yields topic words
        with the fixed seed.
        """
        result = tm.build_topic_words_for_lect(
            TOPIC_MODELLING_CORRECT_ARGS["initial"], "Polack", 1, 10
            )

        self.assertEqual(result, TOPIC_MODELLED_TOKENS_POLACK)


class TestGetTopicWordsForLects(unittest.TestCase):
    """
    Checks the correct behaviour of the get_topic_words_for_lects function.
    """

    def test_get_topic_words_for_lects_negative_case_df(self):
        """
        Checks, whether the function correctly processes the cases,
        when df is not a pandas DataFrame.
        """
        cases = [{"frame": case} for case in INCORRECT_ARGS_BUILD_TOPIC_WORDS_FOR_LECT]
        for case in cases:
            with self.subTest(data=case):
                self.assertRaises(
                    ValueError,
                    tm.get_topic_words_for_lects,
                    case["frame"], tm.LDAParams()
                )

    def test_build_topic_words_for_lect_negative_cases_lda_params(self):
        """
        Checks, whether the function correctly processes the incorrect lda_params argument,
        including incorrect parameter values within it.
        """
        cases = [{"bad_params": case} for case in INCORRECT_ARGS_BUILD_TOPIC_WORDS_FOR_LECT]
        for case in cases:
            with self.subTest(data=case):
                self.assertRaises(
                    ValueError,
                    tm.get_topic_words_for_lects,
                    TOPIC_MODELLING_CORRECT_ARGS["initial"],
                    case["bad_params"]
                )

    def test_get_topic_words_for_lects_positive_case(self):
        """
        Checks, whether the function steadily yields topic words
        with the fixed seed.
        """
        result = tm.get_topic_words_for_lects(
            TOPIC_MODELLING_CORRECT_ARGS["initial"],
            tm.LDAParams(required_topics_start=1)
            )

        self.assertEqual(result, TOPIC_MODELLING_CORRECT_ARGS["topics"])


class TestSaveTopicModellingResults(unittest.TestCase):
    """
    Checks the correctness of the code in the save_topic_modelling function.
    """

    def setUp(self):
        mkdir("exp_1")

    def tearDown(self):
        rmtree("exp_1")

    def test_save_topic_modelling_results_negative_cases_bad_data_frame(self):
        """
        Assures the function rejects the incorrectly given data frame argument.
        """
        cases = [{"frame": case} for case in INCORRECT_ARGS_SAVE_TOPIC_MODELLING_RESULTS]
        for case in cases:
            with self.subTest(data=case):
                self.assertRaises(
                    ValueError,
                    tm.save_topic_modelling_results,
                    TOPIC_MODELLING_CORRECT_ARGS["topics"], case["frame"],
                    TOPIC_MODELLING_CORRECT_ARGS["dir"]
                )


    def test_save_topic_modelling_results_negative_cases_bad_topic_words(self):
        """
        Assures the function rejects the incorrectly given topic_words argument.
        """
        cases = [{"dict": case} for case in INCORRECT_ARGS_SAVE_TOPIC_MODELLING_RESULTS]
        for case in cases:
            with self.subTest(data=case):
                self.assertRaises(
                    ValueError,
                    tm.save_topic_modelling_results,
                    case["dict"],
                    TOPIC_MODELLING_CORRECT_ARGS["result_not_substituted"],
                    TOPIC_MODELLING_CORRECT_ARGS["dir"]
                )

    def test_save_topic_modelling_results_negative_cases_bad_output_dir(self):
        """
        Assures the function rejects the incorrectly given output_dir argument.
        """
        cases = [{"dir": case} for case in INCORRECT_ARGS_SAVE_TOPIC_MODELLING_RESULTS]
        for case in cases:
            with self.subTest(data=case):
                self.assertRaises(
                    ValueError,
                    tm.save_topic_modelling_results,
                    TOPIC_MODELLING_CORRECT_ARGS["topics"],
                    TOPIC_MODELLING_CORRECT_ARGS["result_not_substituted"],
                    case["dir"]
                )


    def test_save_topic_modelling_results_positive_case(self):
        """
        Checks the correct function working in the case all the arguments are correct.
        """
        data_frame = TOPIC_MODELLING_CORRECT_ARGS["result_not_substituted"].reset_index(drop=True)
        topic_words_dict = TOPIC_MODELLING_CORRECT_ARGS["topics"]
        output_dir =  TOPIC_MODELLING_CORRECT_ARGS["dir"]
        expected_topic_words_df = DataFrame(
            topic_words_dict.items(), columns = ['lect', 'topic_words'], dtype='str'
        ).set_index('lect').reset_index(names='lect')

        tm.save_topic_modelling_results(topic_words_dict, data_frame, output_dir)
        result_topic_words_df = read_csv(join(output_dir, 'topic_words_by_lect.csv'))
        result_thematically_modelled_df = read_csv(
            join(output_dir,  'thematic_modelling_output.csv')
            )

        self.assertTrue(result_topic_words_df.equals(expected_topic_words_df))
        self.assertTrue(result_thematically_modelled_df.equals(data_frame))


class TestAddTopicModellingResults(unittest.TestCase):
    """
    Assures the correct functioning of the add_topic_modelling function.
    """

    def setUp(self):
        mkdir("exp_1")

    def tearDown(self):
        rmtree("exp_1")

    def test_add_topic_modelling_results_negative_cases_bad_data_frame(self):
        """
        Assures the function rejects the incorrectly given data frame argument.
        """
        cases = [{"frame": case} for case in INCORRECT_ARGS_SAVE_TOPIC_MODELLING_RESULTS]
        for case in cases:
            with self.subTest(data=case):
                self.assertRaises(
                    ValueError,
                    tm.add_topic_modelling,
                    case["frame"],
                    TOPIC_MODELLING_CORRECT_ARGS["topics"]
                )


    def test_add_topic_modelling_negative_cases_bad_topic_words(self):
        """
        Assures the function rejects the incorrectly given topic_words argument.
        """
        cases = [{"dict": case} for case in INCORRECT_ARGS_SAVE_TOPIC_MODELLING_RESULTS]
        for case in cases:
            with self.subTest(data=case):
                self.assertRaises(
                    ValueError,
                    tm.add_topic_modelling,
                    TOPIC_MODELLING_CORRECT_ARGS["initial"],
                    case["dict"]
                )


    def test_add_topic_modelling_results_negative_cases_bad_substitution(self):
        """
        Assures the function rejects the incorrectly given substitute argument.
        """
        cases = [{"sub": case} for case in INCORRECT_ARGS_SAVE_TOPIC_MODELLING_RESULTS]

        for case in cases:
            with self.subTest(data=case):
                self.assertRaises(
                    ValueError,
                    tm.add_topic_modelling,
                    TOPIC_MODELLING_CORRECT_ARGS["initial"],
                    TOPIC_MODELLING_CORRECT_ARGS["topics"], case["sub"]
                )

    def test_add_topic_modelling_results_positive_case_not_substitute(self):
        """
        Checks the behaviour of the function if the given behaviour pattern
        is to not substitute anything, only to perform topic modelling itself.
        """

        result = tm.add_topic_modelling(
            TOPIC_MODELLING_CORRECT_ARGS["initial"],
            TOPIC_MODELLING_CORRECT_ARGS["topics"]
        )

        self.assertListEqual(list(result["text"]), list(result["text_topic_normalised"]))

    def test_add_topic_modelling_results_positive_case_topic_words_only(self):
        """
        Checks the behaviour of the function if the given behaviour pattern
        is to reserve only the topic modelling results.
        """
        pattern = "topic_words_only"
        expected = [
            tm.return_topic_words(
                TEXT_FOR_TOPIC_MODELLING_POLACK,
                TOPIC_MODELLED_TOKENS_POLACK
                ),
            tm.return_topic_words(
                TEXT_FOR_TOPIC_MODELLING_NOVGOROD,
                TOPIC_MODELLED_TOKENS_NOVGOROD
                )
        ]

        output = tm.add_topic_modelling(
            TOPIC_MODELLING_CORRECT_ARGS["initial"],
            TOPIC_MODELLING_CORRECT_ARGS["topics"],
            pattern
        )
        result = list(output["text_topic_normalised"])

        self.assertEqual(result, expected)


    def test_add_topic_modelling_results_positive_case_substitute(self):
        """
        Checks the behaviour of the function if the given behaviour pattern
        is to reserve everything but the topic modelling results.
        """
        pattern = "substitute"
        expected = [
            tm.clear_stop_words(TEXT_FOR_TOPIC_MODELLING_POLACK, TOPIC_MODELLED_TOKENS_POLACK),
            tm.clear_stop_words(TEXT_FOR_TOPIC_MODELLING_NOVGOROD, TOPIC_MODELLED_TOKENS_NOVGOROD)
            ]

        output = tm.add_topic_modelling(
            TOPIC_MODELLING_CORRECT_ARGS["initial"],
            TOPIC_MODELLING_CORRECT_ARGS["topics"],
            pattern
        )
        result = list(output["text_topic_normalised"])

        self.assertEqual(result, expected)



if __name__ == '__main__':
    unittest.main()
