from __future__ import annotations
from typing import Any

__all__: list[str] = ['Nexus', 'set_fastnnt_threads', 'run_neighbour_net', 'run_neighbor_net']

class Nexus:
    def get_graph_edges(self) -> list[tuple[int, int]]: ...
    def get_labels(self) -> list[str]: ...
    def get_node_positions(self) -> list[list[float]]: ...
    def get_node_translations(self) -> dict[int, int]: ...
    def get_splits_records(self) -> list[Any]: ...

def run_neighbor_net(x: Any, max_iterations: int = 5000, ordering_method: str | None = None, inference_method: str | None = None, labels: list[str] | None = None) -> Nexus: ...
def run_neighbour_net(x: Any, max_iterations: int = 5000, ordering_method: str | None = None, inference_method: str | None = None, labels: list[str] | None = None) -> Nexus: ...
def set_fastnnt_threads(threads: int) -> None: ...
