name: Pre-merge

on:
  pull_request:
    branches: [ dev ]
  
jobs:

  pylint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install pylint
        run: |
          pip install pylint
      - name: Analysing the code with pylint
        run: |
          pylint $(git ls-files '*.py')
  
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install pytest
        run: |
          pip install pytest
          pip install pytest-cov
      - name: Set coverage
        run:
          pytest --cov-report xml:tests/coverage.xml
      - name: Get Cover 
        uses: orgoro/coverage@v3.1
        with:
          coverageFile: tests/coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}